telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.admin.bot.token=${TELEGRAM_ADMIN_BOT_TOKEN}
telegram.admin.bot.username=${TELEGRAM_ADMIN_BOT_USERNAME}

yandex.disk.token=${YANDEX_DISK_TOKEN}
yandex.disk.folder=${YANDEX_DISK_FOLDER}

# Кодировка для логов и консоли
logging.charset.console=UTF-8
logging.charset.file=UTF-8

# PostgreSQL Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/knife_certificates?characterEncoding=UTF-8&useUnicode=true&client_encoding=UTF8}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
